//! Data models shared between the Rust backend and the TypeScript frontend.
//!
//! Every type in this module has an exact counterpart in `src/types.ts`.
//! Serialization uses the conventions the UI expects: enums tagged with
//! `"type"` and `snake_case` field names.

use serde::{Deserialize, Serialize};

/// Authentication method of an SSH profile.
///
/// Serialized as an internally tagged enum:
/// - `{ "type": "password" }`
/// - `{ "type": "key_file", "path": "...", "has_passphrase": true }`
///
/// Neither passwords nor passphrases are ever persisted to JSON: they live in
/// the Windows Credential Manager (see `storage.rs`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AuthMethod {
    /// Password authentication (stored in the Credential Manager).
    Password,
    /// Private key authentication.
    KeyFile {
        /// Absolute path to the private key file (OpenSSH, PKCS#8, ...).
        path: String,
        /// Whether the key is encrypted with a passphrase.
        has_passphrase: bool,
    },
}

/// SSH connection profile (a "server" in the UI).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SshProfile {
    /// Unique identifier (UUID v4 generated by the frontend or the backend).
    pub id: String,
    /// Human readable name shown in the sidebar.
    pub name: String,
    /// Hostname or IP address of the SSH server.
    pub host: String,
    /// SSH port (1-65535).
    pub port: u16,
    /// Remote username.
    pub username: String,
    /// Configured authentication method.
    pub auth_method: AuthMethod,
    /// Creation timestamp (milliseconds since the UNIX epoch).
    pub created_at: u64,
}

/// Local port forwarding rule: `127.0.0.1:local_port -> remote_host:remote_port`
/// tunneled through the SSH session of the associated profile.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortForwardRule {
    /// Unique identifier of the rule.
    pub id: String,
    /// SSH profile used to open the `direct-tcpip` channel.
    pub profile_id: String,
    /// Human readable name (e.g. "PostgreSQL Production").
    pub name: String,
    /// Local port bound on 127.0.0.1.
    pub local_port: u16,
    /// Remote host (as seen from the SSH server).
    pub remote_host: String,
    /// Remote port (as seen from the SSH server).
    pub remote_port: u16,
    /// When `true`, the tunnel starts automatically when Tunnex launches.
    pub auto_start: bool,
}

/// Tunnel lifecycle state.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TunnelState {
    /// Idle.
    Inactive,
    /// SSH negotiation / authentication / local port bind in progress.
    Connecting,
    /// Listening on the local port and forwarding connections.
    Active,
    /// Shutdown requested; closing the SSH session.
    Stopping,
    /// Failure (details in `TunnelStatus::error`).
    Error,
}

/// Real time tunnel status, pushed to the frontend through the Tauri event
/// `tunnel-status` and queryable via `get_active_tunnels_status`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TunnelStatus {
    /// Rule this status belongs to.
    pub rule_id: String,
    /// Current lifecycle state.
    pub state: TunnelState,
    /// Bytes written to the SSH channel (outbound to the remote endpoint).
    pub bytes_sent: u64,
    /// Bytes read from the SSH channel (inbound from the remote endpoint).
    pub bytes_received: u64,
    /// Local TCP connections currently open through the tunnel.
    pub connections: u32,
    /// Milliseconds since the UNIX epoch when the tunnel became `Active`
    /// (`None` when it is not active).
    pub started_at: Option<u64>,
    /// Human readable error message when `state == Error`.
    pub error: Option<String>,
}

impl TunnelStatus {
    /// Empty "inactive" status for a rule with no running tunnel.
    pub fn inactive(rule_id: &str) -> Self {
        Self {
            rule_id: rule_id.to_string(),
            state: TunnelState::Inactive,
            bytes_sent: 0,
            bytes_received: 0,
            connections: 0,
            started_at: None,
            error: None,
        }
    }
}

/// Terminal host used when Tunnex opens a console window.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TerminalKind {
    /// `powershell.exe` — Windows PowerShell 5.1 (always present on Win 10/11).
    WindowsPowershell,
    /// `pwsh.exe` — PowerShell 7+ (cross platform edition).
    PowershellCore,
    /// `wt.exe` — Windows Terminal hosting Windows PowerShell.
    WindowsTerminal,
}

impl Default for TerminalKind {
    fn default() -> Self {
        Self::WindowsPowershell
    }
}

impl TerminalKind {
    /// Executable that will be spawned for this terminal kind.
    pub fn executable(self) -> &'static str {
        match self {
            Self::WindowsPowershell => "powershell.exe",
            Self::PowershellCore => "pwsh.exe",
            Self::WindowsTerminal => "wt.exe",
        }
    }

    /// Shell executable running inside the terminal window.
    pub fn shell_executable(self) -> &'static str {
        match self {
            Self::PowershellCore => "pwsh.exe",
            _ => "powershell.exe",
        }
    }
}

/// Global application preferences, persisted next to profiles and rules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppSettings {
    /// Automatically open a PowerShell console when a tunnel goes active.
    pub open_console_on_connect: bool,
    /// Terminal host used for every console Tunnex spawns.
    pub terminal: TerminalKind,
    /// Keep the console window open after the SSH session ends (`-NoExit`).
    pub keep_console_open: bool,
    /// Pass `-o StrictHostKeyChecking=accept-new` to the `ssh` client so that
    /// first-time hosts do not block the session with an interactive prompt.
    pub accept_new_host_keys: bool,
}

impl Default for AppSettings {
    fn default() -> Self {
        Self {
            open_console_on_connect: true,
            terminal: TerminalKind::WindowsPowershell,
            keep_console_open: true,
            accept_new_host_keys: true,
        }
    }
}

/// Result of spawning a console window, returned to the UI for feedback.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConsoleLaunch {
    /// Terminal executable that was spawned.
    pub terminal: String,
    /// Command line the user sees running inside the console.
    pub command: String,
    /// Window title assigned to the console.
    pub title: String,
}

/// Persistence details surfaced in the "Storage" settings panel.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StorageInfo {
    /// Absolute path of the `config.json` file.
    pub config_path: String,
    /// Service name used in the Windows Credential Manager.
    pub keyring_service: String,
    /// Number of stored profiles.
    pub profiles: usize,
    /// Number of stored rules.
    pub rules: usize,
    /// Tunnels currently running.
    pub active_tunnels: usize,
    /// `true` only in the browser demo mode (no Rust backend).
    pub mock_mode: bool,
}
